#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Erreur: Aucun fichier spécifié"
    echo "Usage: $0 chemin/vers/fichier"
    exit 1
fi

FICHIER="$1"

if [ ! -f "${FICHIER}" ]; then
    echo "Erreur: Le fichier ${FICHIER} n'existe pas"
    exit 1
fi

FICHIER_NAME=$(basename "${FICHIER}" .ova)

OUTPUT_DIR=$(dirname "${FICHIER}")/"${FICHIER_NAME}_output"
mkdir -p "${OUTPUT_DIR}"

echo "Start..."
echo "Conversion du fichier .ova en .tar..."
mv "${FICHIER}" "${OUTPUT_DIR}/${FICHIER_NAME}.tar"
cd "${OUTPUT_DIR}"
sleep 1

echo "Décompression du fichier tar..."
tar -xvf "${FICHIER_NAME}.tar"
sleep 1
rm -rf "${FICHIER_NAME}.tar"
sleep 1

echo "Recherche du fichier VMDK..."
VMDK_FILE=$(find . -name "*.vmdk" -type f)

if [ -z "$VMDK_FILE" ]; then
    echo "Erreur: Aucun fichier VMDK trouvé"
    exit 1
else
    echo "Fichier VMDK trouvé: $VMDK_FILE"
    NAME_FILE=$(basename "$VMDK_FILE" .vmdk)
fi

echo "Conversion du fichier $VMDK_FILE en .qcow2"
qemu-img convert -f vmdk -O qcow2 "$VMDK_FILE" "${NAME_FILE}.qcow2"
sleep 2

echo "Vérification de l'intégrité du fichier ${NAME_FILE}.qcow2"
qemu-img check "${NAME_FILE}.qcow2"
sleep 2

echo "Conversion du fichier ${FICHIER}.ova en ${NAME_FILE}.qcow2 terminée"
